Fix settings code generation error.
Generated code was missing semicolon.

Error was:
```
./obj/main/SOMETARGET/tmp/test.cpp:53:13: error: expected ';' at end of
member declaration
   53 | int64_t v = V
      |             ^
      |              ;
```